<a href="https://colab.research.google.com/github/daniele-lins/sad-thelook-ecommerce/blob/main/sad_thelook_ecommerce.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Tabelas

**1. users (Clientes)**

Contém dados cadastrais e demográficos dos usuários:
* id: Identificador único do usuário (Chave Primária).
* first_name / last_name: Nome e sobrenome.
* email: Endereço de e-mail.
* age: Idade.
* gender: Gênero.
* state / city / country / postal_code: Dados de localização geográfica.
* street_address: Endereço residencial.
* latitude / longitude: Coordenadas geográficas do endereço.
* traffic_source: Canal de marketing pelo qual o usuário chegou (ex: Search, Organic, Facebook).
* created_at: Data e hora de criação da conta.

**2. orders (Pedidos)**

Registra o cabeçalho dos pedidos feitos na plataforma:
* order_id: Identificador único do pedido (Chave Primária).
* user_id: Identificador do usuário que fez a compra (Chave Estrangeira).
* status: Status atual do pedido (ex: Shipped, Complete, Cancelled, Returned).
* gender: Gênero associado ao pedido.
* created_at: Data e hora em que o pedido foi feito.
* returned_at / shipped_at / delivered_at: Datas de retorno, envio e entrega.
* num_of_item: Quantidade total de itens no pedido.

**3. order_items (Itens do Pedido)**

Detelha cada produto individual contido dentro de um pedido:
* id: Identificador único da linha do item (Chave Primária).
* order_id: ID do pedido correspondente (Chave Estrangeira).
* user_id: ID do comprador (Chave Estrangeira).
* product_id: ID do produto comprado (Chave Estrangeira).
* inventory_item_id: ID do item físico específico retirado do estoque (Chave Estrangeira).
* status: Status do item (ex: Processing, Shipped, Complete).
* created_at: Data de criação da linha.
* shipped_at / delivered_at / returned_at: Linha do tempo logística individual do item.
* sale_price: Preço final de venda cobrado pelo produto.

**4. products (Catálogo de Produtos)**

Lista as mercadorias disponíveis para venda na loja de roupas:
* id: Identificador único do produto (Chave Primária).
* cost: Custo de aquisição/fabricação do produto.
* category: Categoria do vestuário (ex: Jeans, Sweaters, Outerwear).
* name: Nome do produto.
* brand: Marca.
* retail_price: Preço sugerido/venda de varejo.
* department: Departamento (ex: Men, Women).
* sku: Código de estoque (Stock Keeping Unit).
* distribution_center_id: Centro de distribuição de onde esse produto é enviado.

**5. inventory_items (Itens de Estoque)**

Controla o estoque físico de produtos nos centros de distribuição:
* id: Identificador único da unidade física em estoque.
* product_id: ID do produto correspondente  (Chave Estrangeira).
* created_at: Quando o item entrou no estoque.
* sold_at: Quando o item foi vendido.
* cost: Custo daquela unidade.
* product_category / product_name / product_brand / product_retail_price / product_department / product_sku: Informações espelhadas do produto para facilidade de consulta.
* product_distribution_center_id: ID do centro de distribuição onde o item está guardado  (Chave Estrangeira).

**6. events (Eventos/Logs Web)**

Registra o comportamento de navegação dos usuários no site ou aplicativo:
* id: Identificador único do evento.
* user_id: ID do usuário (nulo se for um visitante anônimo)  (Chave Estrangeira).
* sequence_number: Ordem do clique dentro da sessão do usuário.
* session_id: Identificador único da sessão de navegação.
* created_at: Data e hora do clique/evento.
* ip_address / city / state / postal_code: Dados geográficos IP da sessão.
* browser: Navegador utilizado (ex: Chrome, Safari).
* traffic_source: Origem do tráfego da sessão.
* uri: O endereço da página da web acessada (ex: /cart, /product/123).
* event_type: Tipo de ação realizada (ex: Home, Department, Product, Cart, Purchase, Cancel).

**7. distribution_centers (Centros de Distribuição)**

Tabela de apoio com as localizações dos armazéns:
* id: Identificador único do centro de distribuição.
* name: Nome da região/cidade do centro.
* latitude / longitude: Localização geográfica do galpão.

# Importação dos dados

In [1]:
import kagglehub
path = kagglehub.dataset_download("mustafakeser4/looker-ecommerce-bigquery-dataset")

Downloading to /root/.cache/kagglehub/datasets/mustafakeser4/looker-ecommerce-bigquery-dataset/1.archive...

100%|██████████| 162M/162M [00:01<00:00, 152MB/s]

Extracting files...

In [2]:
import os
import pandas as pd

# Carregando todos os datasets de forma prática
df_distribution_centers = pd.read_csv(os.path.join(path, 'distribution_centers.csv'))
df_events = pd.read_csv(os.path.join(path, 'events.csv'))
df_products = pd.read_csv(os.path.join(path, 'products.csv'))
df_users = pd.read_csv(os.path.join(path, 'users.csv'))
df_inventory_items = pd.read_csv(os.path.join(path, 'inventory_items.csv'))
df_orders = pd.read_csv(os.path.join(path, 'orders.csv'))
df_order_items = pd.read_csv(os.path.join(path, 'order_items.csv'))

# Exibindo as primeiras linhas de um exemplo (Users)
print("Dataset de Usuários carregado com sucesso!")
df_users.head()

Dataset de Usuários carregado com sucesso!

,id,first_name,last_name,email,age,gender,state,street_address,postal_code,city,country,latitude,longitude,traffic_source,created_at
0,457,Timothy,Bush,timothybush@example.net,65,M,Acre,87620 Johnson Hills,69917-400,Rio Branco,Brasil,-9.945568,-67.83561,Search,2022-07-19 13:51:00+00:00
1,6578,Elizabeth,Martinez,elizabethmartinez@example.com,34,F,Acre,1705 Nielsen Land,69917-400,Rio Branco,Brasil,-9.945568,-67.83561,Search,2023-11-08 18:49:00+00:00
2,36280,Christopher,Mendoza,christophermendoza@example.net,13,M,Acre,125 Turner Isle Apt. 264,69917-400,Rio Branco,Brasil,-9.945568,-67.83561,Email,2019-08-24 06:10:00+00:00
3,60193,Jimmy,Conner,jimmyconner@example.com,64,M,Acre,0966 Jose Branch Apt. 008,69917-400,Rio Branco,Brasil,-9.945568,-67.83561,Search,2020-02-15 11:26:00+00:00
4,64231,Natasha,Wilson,natashawilson@example.net,25,F,Acre,20798 Phillip Trail Apt. 392,69917-400,Rio Branco,Brasil,-9.945568,-67.83561,Search,2020-03-13 06:45:00+00:00

# Tratamento dos dados

In [53]:
import duckdb

query = """
SELECT
  u.id AS user_id,
  u.age,
  u.gender,
  u.country,
  u.state,
  u.traffic_source,
  u.created_at AS user_created_at,
  o.order_id,
  o.status AS order_status,
  o.created_at AS order_created_at,
  o.shipped_at,
  o.delivered_at,
  o.num_of_item AS order_num_of_item,
  oi.id AS order_item_id,
  oi.status AS order_item_status,
  oi.sale_price AS order_item_sale_price,
  COALESCE(p.name, 'Sem Nome') AS product_name,
  p.category AS category,
  p.department AS product_department,
  COALESCE(p.brand, 'Sem Marca') AS brand,
  p.cost AS product_cost,
  p.retail_price AS product_retail_price,
  dc.name AS distribution_center_name,
  ii.id AS item_id,
  ii.created_at AS item_in_sku_at,
  ii.cost AS item_cost
FROM df_order_items oi
INNER JOIN df_orders o ON o.order_id = oi.order_id
LEFT JOIN df_users u ON u.id = oi.user_id
LEFT JOIN df_products p ON p.id = oi.product_id
LEFT JOIN df_inventory_items ii ON ii.id = oi.inventory_item_id
LEFT JOIN df_distribution_centers dc ON dc.id = p.distribution_center_id
WHERE o.status = 'Complete'
  AND o.created_at IS NOT NULL
  AND u.created_at IS NOT NULL
"""

df_result = duckdb.query(query).df()
print(df_result.info())
df_result.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 44502 entries, 0 to 44501
Data columns (total 26 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   user_id                   44502 non-null  int64
 1   age                       44502 non-null  int64
 2   gender                    44502 non-null  object
 3   country                   44502 non-null  object
 4   state                     44502 non-null  object
 5   traffic_source            44502 non-null  object
 6   user_created_at           44502 non-null  datetime64[us, Etc/UTC]
 7   order_id                  44502 non-null  int64
 8   order_status              44502 non-null  object
 9   order_created_at          44502 non-null  datetime64[us, Etc/UTC]
 10  shipped_at                44502 non-null  object
 11  delivered_at              44502 non-null  object
 12  order_num_of_item         44502 non-null  int64
 13  order_item_id             44502 non-null  int64
 14  order_item_status         44502 non-null  object
 15  order_item_sale_price     44502 non-null  float64
 16  product_name              44502 non-null  object
 17  category                  44502 non-null  object
 18  product_department        44502 non-null  object
 19  brand                     44502 non-null  object
 20  product_cost              44502 non-null  float64
 21  product_retail_price      44502 non-null  float64
 22  distribution_center_name  44502 non-null  object
 23  item_id                   44502 non-null  int64
 24  item_in_sku_at            44502 non-null  object
 25  item_cost                 44502 non-null  float64
dtypes: datetime64[us, Etc/UTC](2), float64(4), int64(6), object(14)
memory usage: 8.8+ MB
None

,user_id,age,gender,country,state,traffic_source,user_created_at,order_id,order_status,order_created_at,...,product_name,category,product_department,brand,product_cost,product_retail_price,distribution_center_name,item_id,item_in_sku_at,item_cost
0,22002,44,F,Australia,Queensland,Search,2023-09-19 00:46:00+00:00,27520,Complete,2024-01-11 00:46:00+00:00,...,(ONE) 1 Satin Headband,Accessories,Women,Funny Girl Designs,2.76804,6.99,Philadelphia PA,107800,2021-04-28 18:16:00+00:00,2.76804
1,48646,13,F,United States,Louisiana,Search,2019-08-29 03:21:00+00:00,60836,Complete,2023-01-04 03:21:00+00:00,...,(One) CHEER Rhinestone Studded Stretch Headband,Accessories,Women,Funny Girl Designs,2.24625,5.99,Philadelphia PA,238662,2020-08-11 06:58:00+00:00,2.24625
2,11811,48,F,China,Fujian,Search,2022-05-20 08:11:00+00:00,14755,Complete,2022-10-14 08:11:00+00:00,...,(Set of 4) 2.5 Glitter Cotton Stretch Headbands,Accessories,Women,Funny Girl Designs,4.11026,10.99,Philadelphia PA,57533,2020-08-05 00:40:00+00:00,4.11026
3,37322,13,M,United States,Ohio,Search,2019-10-16 18:13:00+00:00,46644,Complete,2023-04-02 18:13:00+00:00,...,1 1/2 In. Original Perry Suspenders,Accessories,Men,Perry,6.57410,16.90,Memphis TN,182948,2023-01-09 00:52:00+00:00,6.57410
4,69413,36,M,United States,Georgia,Search,2021-11-16 18:07:00+00:00,87096,Complete,2022-07-10 18:07:00+00:00,...,100% Cowhide Leather Black Leather Belt Snap o...,Accessories,Men,Belts.com,3.51648,9.99,Memphis TN,341356,2021-12-13 12:23:00+00:00,3.51648

# Dashboard (Sumarização)

## Big numbers
- Receita total acumulada
- Lucro Bruto Total e Margem Bruta (%)
- Ticket Médio por Pedido (AOV)
- LTV Médio Geral por Cliente
- Taxa de Recompra (%)
- Média de Itens por Pedido (UPT)

## Gráficos
**Comparativo de Receita e Margem por Canal (** **traffic\_source** **)**:
* **Tipo de Gráfico**: *Gráfico de Barras Agrupadas*.
* **Por que**: Compara lado a lado o faturamento bruto versus o lucro real de cada canal de aquisição.

**Evolução Mensal do Faturamento por Canal de Origem**:
* **Tipo de Gráfico**: *Gráfico de Linhas*.
* **Por que**: Mostra tendências de crescimento de receita ao longo do tempo (`order_created_at`) separadas por origem.

**LTV e Ticket Médio por Origem de Tráfego**:
* **Tipo de Gráfico**: *Gráfico de Colunas*.
* **Por que**: Evidencia se clientes vindos de canais pagos (ex: Facebook) gastam mais por compra/ao longo da vida do que os de busca orgânica.

**Desempenho por Categoria (`category`), Marca (`brand`) e Departamento (`product_department`)**:
* **Tipo de Gráfico**: *Gráfico de Treemap ou Colunas Horizontais*.
* **Por que**: Identifica rapidamente os produtos campeões de vendas e de maior margem para destacá-los nos anúncios.

**Distribuição Geográfica e Demográfica (`country`, `state`, `gender`, `age`)**:
* **Tipo de Gráfico**: *Mapa Coroplético e Pirâmide Etária / Histograma*.
* **Por que**: Mapeia onde estão os melhores compradores para direcionar a segmentação geográfica e demográfica dos anúncios pagos.